/**
 * Shared helpers for cross-assistant adapters.
 * Zero external dependencies. Node >= 18.
 */

const fs = require('fs');
const path = require('path');
const { GENERATED_MARK } = require('../ops');
const caveman = require('../caveman');
const { parse } = require('../frontmatter');

/**
 * Generate one symlink or file op per item into destination directory.
 */
function linkEach(items, dir, { agent, why, ext = '', nameKey = 'name' }) {
  return (items || []).map(item => ({
    kind: 'symlink',
    path: path.join(dir, item[nameKey] + ext),
    target: item.kind === 'skill' ? item.dir : item.file,
    agent,
    why: why || `${item.kind} ${item.name}`
  }));
}

/**
 * Generate managed block content for a global assistant instruction file.
 */
function globalBlock(ctx, { importSyntax = false } = {}) {
  const root = ctx.tilde ? ctx.tilde(ctx.root) : ctx.root;
  const config = ctx.config || {};
  const mode = (config.caveman && config.caveman.mode) || 'full';
  const cave = caveman.statement(mode, { scope: 'global' });

  if (importSyntax) {
    const importPath = process.platform === 'win32'
      ? path.resolve(ctx.root, 'GLOBAL.md').replace(/\\/g, '/')
      : `${root}/GLOBAL.md`;
    return [
      `@${importPath}`,
      `Global skills, agents, and rules reside in ${root}/. Invoke a skill by name (e.g., "use the create-prd skill"). In a project repository, docs/ai/AGENT-CORE.md is canonical and wins on conflict.`,
      cave
    ].join('\n');
  }

  return [
    `Personal operating rules: Read ${root}/GLOBAL.md before acting on any task.`,
    `Global skills, agents, and rules reside in ${root}/{skills,agents,rules}/. Invoke a skill by name (e.g., "use the create-prd skill"). Resolve from project vendored copies first, then ${root}.`,
    `In a project repository, docs/ai/AGENT-CORE.md (reachable via AGENTS.md, CLAUDE.md, GEMINI.md) is canonical and wins on conflict; global principles fill gaps.`,
    cave
  ].join('\n');
}

/**
 * Standard header comment for generated markdown files.
 */
function mdHeader(cmd = 'gabby link') {
  return `<!-- ${GENERATED_MARK} -- DO NOT EDIT: regenerated by \`${cmd}\`. Project-scoped changes go in docs/ai/ (ENGINEERING.md § 0 for rule overrides). This is not an instruction to edit global root; global files change only from a session opened there (RULE-SCOPE-001). -->\n`;
}

/**
 * Pointer file content dropped into a project for agents that read a rules directory.
 */
function corePointer(ctx) {
  const root = ctx.tilde ? ctx.tilde(ctx.root) : ctx.root;
  return [
    mdHeader(),
    '# Canonical Instruction Source',
    '',
    'Read `docs/ai/AGENT-CORE.md` before doing anything in this repository. It is the one canonical instruction source; `AGENTS.md`, `CLAUDE.md`, `GEMINI.md` and `.github/copilot-instructions.md` are links to it.',
    '',
    `Personal global skills, agents, and rules live in \`${root}\` when present (see \`GLOBAL.md\` there). Project documentation wins on conflict.`,
    ''
  ].join('\n');
}

/**
 * Project pointer for rule-directory agents: the effective caveman mode for this repo + digest.
 */
function cavemanPointer(ctx, dir) {
  const eff = caveman.effective(dir, ctx.config);
  const rulePath = path.join(ctx.root, 'rules', 'caveman.md');
  let body = '';
  if (fs.existsSync(rulePath)) {
    const raw = fs.readFileSync(rulePath, 'utf8');
    body = parse(raw).body.replace(/<!--[\s\S]*?-->\n?/g, '').trim();
  }

  return [
    mdHeader('gabby link / gabby caveman'),
    `# Caveman — Effective mode for this project: **${eff.mode}** (${eff.source === 'project' ? '.caveman.json' : eff.source === 'env' ? 'CAVEMAN_DEFAULT_MODE' : 'global default'})`,
    '',
    `Change it with \`gabby caveman <off|lite|full|ultra|inherit>\` in this repository, or edit \`.caveman.json\` (\`{"defaultMode": "..."}\`).`,
    '',
    body,
    ''
  ].join('\n');
}

module.exports = {
  linkEach,
  globalBlock,
  mdHeader,
  corePointer,
  cavemanPointer
};
