/**
 * Google Gemini CLI assistant adapter.
 * Zero external dependencies. Node >= 18.
 */

const path = require('path');
const { linkEach, globalBlock } = require('./common');
const { GENERATED_MARK } = require('../ops');

const id = 'gemini';
const name = 'Gemini CLI';

function wrapper(ctx, skill) {
  const esc = s => (s || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return [
    `# ${GENERATED_MARK} -- DO NOT EDIT: regenerated by \`gabby install\` from the ${skill.name} skill frontmatter`,
    `description = "${esc(skill.description)}"`,
    'prompt = """',
    `Activate the \`${skill.name}\` skill (~/.gemini/skills/${skill.name}/SKILL.md) and follow it completely.`,
    '',
    'Task: {{args}}',
    '"""',
    ''
  ].join('\n');
}

function global(ctx) {
  const home = ctx.homes.gemini;
  const reg = ctx.registry || {};
  const config = ctx.config || {};
  const wrappersConfig = config.wrappers || {};

  const ops = [
    ...linkEach(reg.skills || [], path.join(home, 'skills'), { agent: id }),
    {
      kind: 'managed',
      path: path.join(home, 'GEMINI.md'),
      inner: globalBlock(ctx),
      agent: id,
      why: 'global GEMINI.md -> GLOBAL.md (shared with Antigravity)'
    }
  ];

  if (wrappersConfig.gemini !== false && reg.skills) {
    for (const s of reg.skills.filter(s => s.invocable)) {
      ops.push({
        kind: 'file',
        path: path.join(home, 'commands', `${s.name}.toml`),
        content: wrapper(ctx, s),
        agent: id,
        why: `Gemini command /${s.name}`
      });
    }
  }

  return ops;
}

function project(ctx, dir) {
  return [
    {
      kind: 'symlink',
      path: path.join(dir, 'GEMINI.md'),
      target: 'docs/ai/AGENT-CORE.md',
      agent: id,
      why: 'Gemini CLI entry point -> AGENT-CORE'
    }
  ];
}

module.exports = {
  id,
  name,
  global,
  project,
  wrapper
};
